framework:
    cache:
        pools:
            fio.static_data:
                adapter: cache.app
                default_lifetime: 86400
            fio.dynamic_data:
                adapter: cache.app
                default_lifetime: 300
